game/apps/characters/urls.py
from django.conf.urls import patterns, url
from .views import CharacterDetail, CharacterCreate, ShopItems, CreateMatch

urlpatterns = patterns('',
    url(r'^(?P<pk>\d+)$', CharacterDetail.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/create/$', CreateMatch.as_view(), name='create'),
    url(r'^create/$', CharacterCreate.as_view(), name='create_char'),
    url(r'^(?P<pk>\d+)/shop/$', ShopItems.as_view(), name='shop'),
)

game/apps/match/urls.py
from django.conf.urls import patterns, url
from .views import CreateMatch, MatchDetail, AttackForm, MatchList

urlpatterns = patterns('',
    url(r'^(?P<pk>\d+)/attack/$', AttackForm.as_view(), name='attack'),
    url(r'^$', MatchList.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', MatchDetail.as_view(), name='detail'),
)

game/apps/userprofile/urls.py
from django.conf.urls import patterns, url
from .views import UserProfilePage

urlpatterns = patterns('',
    url(r'^settings/$', UserProfilePage.as_view(), name="profile_page"),
)

game/urls.py
from django.conf.urls import patterns, include, url
from .views import Homepage
from game.apps.characters.views import CharacterLeaderboard
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^match/', include('game.apps.match.urls',  namespace="match")),
    url(r'^character/', include('game.apps.characters.urls', namespace="character")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', Homepage.as_view(), name='homepage'),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^leaderboard/$', CharacterLeaderboard.as_view(), name="leaderbaord"),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
)

game/apps/enemies/models.py
from django.db import models


class Enemy(models.Model):
    name = models.CharField(
        max_length=150,
        )
    level = models.PositiveIntegerField(
        max_length=16,
        default=1
        )
    health = models.PositiveIntegerField(
        max_length=16,
        default=100
        )

    top = models.PositiveIntegerField(
        max_length=16,
        null=True,
        )
    left = models.PositiveIntegerField(
        max_length=16,
        null=True,
    )
    def __unicode__(self):
        return self.name

game/apps/match/models.py
from django.db import models
from game.apps.enemies.models import Enemy
from game.apps.characters.models import Character, Type


class Match(models.Model):

    character = models.ForeignKey(
        Character,
        )

    enemy = models.ForeignKey(
        Enemy,
        )

    character_health = models.PositiveIntegerField(
        "Current Character Health",
        max_length=16,
        blank=True,
        )

    enemy_health = models.PositiveIntegerField(
        "Current Enemy Health",
        max_length=16,
        blank=True,
        )

    resource = models.PositiveIntegerField(
        max_length=200,
        default=1,
        )

    finished = models.BooleanField(
        default=False,
        )

    class Meta:
        verbose_name_plural = "Matches"

    def __unicode__(self):
        return self.character.name

    @models.permalink
    def get_absolute_url(self):
            return ("match:detail", (), {
                "pk": self.pk
            })


class Spell(models.Model):

    name = models.CharField(
        max_length=140,
        )
    type = models.ForeignKey(
        Type,
        null=True,
    )
    description = models.TextField(
        null=True,
        )

    damage = models.PositiveIntegerField(
        max_length=15,
        )

    level_required = models.PositiveIntegerField(
        max_length=15,
        null=True,
        )

    turn_cooldown = models.PositiveIntegerField(
        max_length=200,
        )

    def __unicode__(self):
        return self.name


class Attack(models.Model):

    match = models.ForeignKey(
        Match
        )

    spell = models.ForeignKey(
        Spell
        )

    enemy_return_spell = models.ForeignKey(
        Spell,
        null=True,
        related_name='reliation'
        )

    damage_dealt = models.PositiveIntegerField(
        max_length=200,
        null=True,
        )

    damage_taken = models.PositiveIntegerField(
        max_length=200,
        null=True,
        )

    time = models.TimeField(
        null=True,
        )

game/apps/userprofile/models.py
from django.db import models
import watson
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class UserProfile(models.Model):
    user = models.OneToOneField(
        User
    )

    def __unicode__(self):
        return self.user.email

User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])
watson.register(UserProfile)


def create_profile(sender, **kw):
    user = kw["instance"]
    if kw["created"]:
        up = UserProfile(user=user)
        up.save()
post_save.connect(create_profile, sender=User)

game/apps/characters/forms.py
from django import forms
from .models import Character
from game.apps.match.models import Match

class CharacterCreate(forms.ModelForm):
    error_css_class = "error"

    class Meta:
        model = Character
        exclude = ['user', 'health', 'xp']


class CreateMatch(forms.ModelForm):

    class Meta:
        model = Match
        exclude = ['character_health', 'enemy_health', 'resource', 'character']

game/apps/match/forms.py
from django import forms
from .models import Match, Attack


class CreateMatch(forms.ModelForm):

    class Meta:
        model = Match
        exclude = ['character_health', 'enemy_health', 'resource']


class AttackForm(forms.ModelForm):

    class Meta:
        model = Attack
        exclude = ['time', 'enemy_return_spell', 'match', 'damage_dealt', 'damage_taken']

game/apps/userprofile/forms.py
from django import forms
from .models import UserProfile


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('user',)

game/apps/characters/views.py
from django.views.generic import DetailView, CreateView, ListView
from .models import Character, Type, Item
from .forms import CharacterCreate, CreateMatch
from game.apps.match.models import Match, Enemy
from django.views.generic.edit import ModelFormMixin
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from game.apps.match.helpers import calculate_player_health, calculate_boss_health


class ShopItems(ListView):
    model = Item

    def get_context_data(self, **kwargs):
        context = super(ShopItems, self).get_context_data(**kwargs)
        # Need to filter by Class(type)
        context['item_list'] = Item.objects.all()
        for item in context['item_list']:
            if  self.request.user >= item.level_required:
                pass
            else:
                context['insufficient'] = "Insufficient Level"

        return context


class CharacterLeaderboard(ListView):
    model = Character

    def get_context_data(self, **kwargs):
        context = super(CharacterLeaderboard, self).get_context_data(**kwargs)
        context['character_list'] = Character.objects.all().order_by('-xp')[:100]
        return context


class CharacterDetail(DetailView):
    model = Character


class CreateMatch(CreateView):
    model = Match
    form_class = CreateMatch

    def get_context_data(self, **kwargs):
        context = super(CreateMatch, self).get_context_data(**kwargs)
        character = get_object_or_404(
            Character,
            pk=self.kwargs.get('pk'),
            user=self.request.user
        )
        context['character'] = character

        context['enemys'] = Enemy.objects.all()
        return context

    def form_valid(self, form):
        Form = form.save(commit=False)
        boss = form.cleaned_data['enemy']
        Form.enemy_health = calculate_boss_health(boss)
        Form.resource = 1
        character = Character.objects.get(pk=self.kwargs['pk'])
        Form.character = character
        Form.character_health = calculate_player_health(character)
        self.object = form.save()
        return super(ModelFormMixin, self).form_valid(form)


class CharacterCreate(CreateView):
    model = Character
    form_class = CharacterCreate

    def form_valid(self, form):
        charactercreate = form.save(commit=False)
        charactercreate.user = self.request.user
        self.object = form.save()
        return super(ModelFormMixin, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CharacterCreate, self).get_context_data(**kwargs)
        context['types'] = Type.objects.all()
        return context

    def get_success_url(self):
        return reverse('character:detail', kwargs={'pk': self.object.pk})


#class DeleteCharacter(UpdateView):
#    model = Character

game/apps/enemies/views.py
from django.shortcuts import render

# Create your views here.

game/apps/match/views.py
from django.views.generic import CreateView, DetailView, ListView
from django.views.generic.edit import ModelFormMixin
from .models import Match, Attack
from game.apps.characters.models import Character
from game.apps.enemies.models import Enemy
from .forms import CreateMatch, AttackForm
from .models import Spell
from django.utils.timezone import now
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse
from .helpers import calculate_player_damage, calculate_boss_damage, calculate_player_health,  calculate_boss_health, calculate_xp


class CreateMatch(CreateView):
    model = Match
    form_class = CreateMatch

    def get_context_data(self, **kwargs):
        context = super(CreateMatch, self).get_context_data(**kwargs)
        context['characters'] = Character.objects.filter(user=self.request.user)
        context['enemys'] = Enemy.objects.all()
        return context

    def form_valid(self, form):
        Form = form.save(commit=False)
        boss = form.cleaned_data['enemy']
        Form.enemy_health = calculate_boss_health(boss)
        Form.resource = 1
        character = form.cleaned_data['character']
        Form.character_health = calculate_player_health(character)
        self.object = form.save()
        return super(ModelFormMixin, self).form_valid(form)


class MatchDetail(DetailView):
    model = Match

    def get_context_data(self, **kwargs):
        context = super(MatchDetail, self).get_context_data(**kwargs)

        context['spells'] = Spell.objects.filter(
            type=self.object.character.type,
            level_required__lte=context['match'].character.level_data()['current_level'],
        )

        match = get_object_or_404(
            Match,
            pk=self.kwargs.get('pk'),
            character__user=self.request.user,
        )

        if self.object.enemy_health == 0:
            context['condition'] = "win"
        else:
            if self.object.character_health == 0:
                context['condition'] = "loose"
            else:
                pass

        context['match'] = match

        cooldown = False

        for spell in context['spells']:
            attack_history_list = Attack.objects.filter(match=122).order_by('-time')[:spell.turn_cooldown]
            print attack_history_list
            for attack_history in attack_history_list:
                if attack_history.spell == attack_history_list:
                    cooldown = True
                    print cooldown
                    print attack_history.spell
                    context['cooldown'] = cooldown
                    break
                else:
                    cooldown = False
                    print cooldown
                    print attack_history.spell
                    context['cooldown'] = cooldown
        return context


class MatchList(ListView):
    model = Match


class AttackForm(CreateView):
    model = Attack
    form_class = AttackForm

    def get_context_data(self, **kwargs):
        context = super(AttackForm, self).get_context_data(**kwargs)
        match = get_object_or_404(
            Match,
            pk=self.kwargs.get('pk'),
            character__user=self.request.user
        )
        context['match'] = match
        return context

    def form_valid(self, form):
        spell = form.cleaned_data['spell']
        attackform = form.save(commit=False)
        match = Match.objects.get(id=self.kwargs['pk'])
        boss_spell = Spell.objects.filter(level_required__lte=match.enemy.level).order_by('?')[0]
        character_level = match.character.level_data()['current_level']
        attackform.enemy_return_spell = boss_spell
        character = match
        attackform.selected_spell = spell
        cooldown = False
        attack_history_list = Attack.objects.filter(match=match).order_by('-time')[:spell.turn_cooldown]

        for attack_history in attack_history_list:
            if attack_history.spell == spell:
                cooldown = True
                break
            else:
                cooldown = False

        if spell.level_required <= character_level and spell.type == match.character.type and cooldown == False:

            if match.finished is False:
                if match.enemy_health <= calculate_player_damage(character, spell):
                    match.enemy_health = 0
                    match.character.xp = match.character.xp + calculate_xp(match)
                    match.finished = True
                else:
                    if match.character_health <= calculate_boss_damage(boss_spell, match):
                        match.character_health = 0
                        match.finished = True
                    else:
                        match.enemy_health = match.enemy_health - calculate_player_damage(character, spell)
                        match.character_health = match.character_health - calculate_boss_damage(boss_spell, match)

            else:
                return super(ModelFormMixin, self).form_valid(form)

            attackform.damage_dealt = calculate_player_damage(match, spell)
            attackform.damage_taken = calculate_boss_damage(boss_spell, match)

            attackform.match = match
            attackform.time = now()
            match.save()
            match.character.save()
            self.object = attackform.save()

            return super(ModelFormMixin, self).form_valid(form)
        else:
            return super(ModelFormMixin, self).form_valid(form)

    def get_success_url(self):
        return reverse('match:detail', kwargs={'pk': self.kwargs['pk']})

game/apps/userprofile/views.py
from django.views.generic import UpdateView
from django.views.generic.edit import ModelFormMixin
from .forms import UserProfileForm
from .models import UserProfile


class UserProfilePage(UpdateView):
    model = UserProfile
    success_url = '/settings/'
    form_class = UserProfileForm

    def form_valid(self, form):
        self.object = form.save()
        return super(ModelFormMixin, self).form_valid(form)

game/views.py
from django.views.generic import ListView
from game.apps.characters.models import Character

class Homepage(ListView):
    model = Character
    template_name = 'site/homepage.html'

    def get_context_data(self, **kwargs):
        context = super(Homepage, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated():
            context['characters'] = Character.objects.filter(user=self.request.user)
        else:
            pass
        return context

game/templates/match/attack_form.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="large-6 columns">
        <h1>Attack</h1>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Attack" class="button">
        </form>
    </div>
</div>
{% endblock content %}

game/templates/match/match_detail.html
{% extends "base.html" %}
{% block url %}{{ match.character.get_absolute_url }}{% endblock %}
{% block content %}
<style type="text/css">

</style>


{% if condition %}
{% if condition == "win" %}
    <center><h1>You Won!</h1></center>
{% endif %}
{% if condition == "loose" %}
   <center> <h1>You lost!</h1></center>
{% endif %}
{% else %}
<div class="row">
    <div class="large-12 columns">
        <div class="large-5 columns">
            <h1>
                {{ match.character }}
                <small>{{ match.character_health }}</small>
            </h1>
        </div>

        <div class="large-2 columns">
            <center>
                <h1><small>vs</small></h1>
            </center>
        </div>
        <div class="large-5 columns">
            <h1 class="right">
                {{ match.enemy }}
                <small>{{ match.enemy_health }}</small>
            </h1>
        </div>
        <div class="large-5 columns">
            <small class="xp-level">Level {% with level_data=match.character.level_data %}{{ level_data.current_level }} {% endwith %}</small>
        </div>
        <div class="large-5 columns">
            <small class="xp-level-right">Level {{ match.enemy.level }} </small>
        </div>
    </div>
</div>
<hr>
<div class="row">
    <div class="large-12 columns">
        <div class="match">
            This is where the game takes place!
            <div class="tooltip">edit me</div>
        <div class="panel historybox">
            <h3>History</h3>
            <hr>
            {% for attack in match.attack_set.all %}
            <li>Sent {{ attack.damage_dealt }}, Took {{ attack.damage_taken }}</li>
            {% endfor %}
        </div>


        </div>
    </div>
</div>
<div class="row">
    <div class="large-12 columns">
        <form action="/match/{{ match.id }}/attack/" method="post">
            {% csrf_token %}
            <ul class="spell_list">
                {% for spell in spells %}
                    <li>
                        <a data-tooltip aria-haspopup="true" class="has-tip" title="Damage: {{ spell.damage }}
                        Cooldown {{ spell.turn_cooldown }} {{ spell.cooldown }}">
                        <input type="radio" name="spell" value="{{ spell.id }}" id="{{ spell.name }}{{ spell.id }}">
                        <label for="{{ spell.name }}{{ spell.id }}" class="testlabel" required>{{ spell.name }}</label>
                        </a>
                    </li>
                {% endfor %}
                    <li>

                        <input type="radio" name="spell" value="{{ spell.id }}" id="{{ spell.name }}{{ spell.id }}" class="disabled"><label for="{{ spell.name }}{{ spell.id }}" class="testlabel disabled">Disabled Spell</label>
                    </li>
            </ul>
            <div class="large-12 columns left">
                <hr>
                <input type="submit" value="End Turn" class="button">
            </div>
        </form>
    </div>
    <div class="large-5 columns">

    </div>
{% endif %}
{% endblock content %}
{% block js %}
{% endblock %}

game/templates/match/match_form.html
{% extends "base.html" %}
{% block url %}{{ character.get_absolute_url }}{% endblock %}
{% block content %}
<div class="row">
    <div class="large-12 columns"><br><span class="right">You are playing as {{ character }}</span><br><hr></div>
    <div class="large-12 columns">
        <form action="" method="post">
            <div class="panel map">
                {% csrf_token %}
                {% for enemy in enemys %}
                    <li>
                        <input type="radio" name="enemy" value="{{ enemy.id }}" id="{{ enemy.name }}{{ enemy.id }}">
                        <label for="{{ enemy.name }}{{ enemy.id }}" class="enemymap" style="top: {{ enemy.top }}px; left: {{ enemy.left }}px" required>
                            {{ enemy.name }} ({{ enemy.level }})
                        </label>
                    </li>
                {% endfor %}
            </div>
            <hr>
            <input type="submit" value="Start Match" class="button">
        </form>
    </div>
</div>
{% endblock content %}

game/templates/match/match_list.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <h1>Matches</h1>
    <p>All of the matches, these will be filtered to only yours soon</p>
    {% for match in match_list  %}
        <a href="/match/{{ match.id }}">{{ match.character }}</a>
    {% endfor %}
</div>
{% endblock content %}