game/apps/characters/urls.py
from django.conf.urls import patterns, url
from .views import CharacterDetail, CharacterCreate, ShopItems, CreateMatch

urlpatterns = patterns('',
    url(r'^(?P<pk>\d+)$', CharacterDetail.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/create/$', CreateMatch.as_view(), name='create'),
    url(r'^create/$', CharacterCreate.as_view(), name='create_char'),
    url(r'^(?P<pk>\d+)/shop/$', ShopItems.as_view(), name='shop'),
)

game/apps/match/urls.py
from django.conf.urls import patterns, url
from .views import CreateMatch, MatchDetail, AttackForm, MatchList

urlpatterns = patterns('',
    url(r'^(?P<pk>\d+)/attack/$', AttackForm.as_view(), name='attack'),
    url(r'^$', MatchList.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', MatchDetail.as_view(), name='detail'),
)

game/apps/userprofile/urls.py
from django.conf.urls import patterns, url
from .views import UserProfilePage

urlpatterns = patterns('',
    url(r'^settings/$', UserProfilePage.as_view(), name="profile_page"),
)

game/urls.py
from django.conf.urls import patterns, include, url
from .views import Homepage
from game.apps.characters.views import CharacterLeaderboard
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^match/', include('game.apps.match.urls',  namespace="match")),
    url(r'^character/', include('game.apps.characters.urls', namespace="character")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', Homepage.as_view(), name='homepage'),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^leaderboard/$', CharacterLeaderboard.as_view(), name="leaderbaord"),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
)

game/apps/characters/models.py
from django.contrib.auth.models import User
from django.db import models


LEVELS = [
    (1, 200),
    (2, 400),
    (3, 600),
    (4, 800),
    (5, 1000),
    (6, 1200),
    (7, 1400),
    (8, 1600),
    (9, 1800),
    (10, 2000),
]


class InvBag(models.Model):

    name = models.CharField(
        max_length=200,
    )

    level_required = models.PositiveIntegerField(
        max_length=100
        )

    worth = models.DecimalField(
        decimal_places=2,
        max_digits=100,
    )

    spaces = models.PositiveIntegerField(
        max_length=100,
    )

    def __unicode__(self):
        return self.name


class Type(models.Model):

    name = models.CharField(
        max_length=150,
        unique=True,
    )

    description = models.TextField(
        blank=True,
    )

    def __unicode__(self):
        return self.name


class Character(models.Model):

    user = models.ForeignKey(
        User,
    )

    name = models.CharField(
        max_length=150,
        unique=True,
    )

    type = models.ForeignKey(
        Type,
    )

    # This will get removed / ignored when you have armor
    health = models.PositiveIntegerField(
        max_length=16,
        default=100,
    )

    xp = models.PositiveIntegerField(
        "Current XP",
        max_length=16,
        default=0,
        blank=True,
    )

    is_deleted = models.BooleanField(
        default=False,
        )
    inv_bag = models.ForeignKey(
        InvBag,
        null=True,
        blank=True,
        )
    class Meta:
        ordering = ['name']

    def __unicode__(self):
        return self.name

    def level_data(self):
        total_xp = self.xp

        for level in LEVELS:
            # Subtract the amount of XP required to leave this level from the
            # total XP. This will determine whether we're still on this level
            # or not.
            if total_xp - level[1] < 0:
                return {
                    'current_level': level[0],
                    'progress': total_xp,
                    'total_xp_required': level[1],
                    'xp_percentage': (float(total_xp) / level[1]) * 100
                }
            else:
                total_xp = total_xp - level[1]

        # If we haven't returned at this point, we're at max level.
        final_level = LEVELS[-1]
        if total_xp > final_level[1]:
            total_xp = final_level[1]

        return {
            'current_level': final_level[0],
            'progress': total_xp,
            'total_xp_required': final_level[1],
            'xp_percentage': (float(total_xp) / final_level[1]) * 100
        }

    @models.permalink
    def get_absolute_url(self):
            return ("character:detail", (), {
                "pk": self.pk
            })


class Group(models.Model):
    name = models.CharField(
        max_length=200,
        unique=True,
    )

    def __unicode__(self):
        return self.name


class Item(models.Model):

    name = models.CharField(
        max_length=200,
        unique=True,
    )

    image = models.ImageField(
        upload_to='items',
        blank=True,
        null=True,
        )

    group = models.ForeignKey(
	    Group,
    )

    worth = models.DecimalField(
	    decimal_places=2,
        max_digits=100,
    )

    for_class = models.ForeignKey(
	    Type,
    )

    level_required = models.PositiveIntegerField(
        max_length=200,
    )

    damage = models.PositiveIntegerField(
        max_length=200,
        default=0,
        null=True,
    )

    healing = models.PositiveIntegerField(
        max_length=200,
        default=0,
        null=True,
    )

    armor = models.PositiveIntegerField(
        max_length=200,
        default=0,
        null=True,
    )
    def __unicode__(self):
        return self.name


class CharacterItem(models.Model):
    character = models.ForeignKey(
        Character
        )
    item = models.ForeignKey(
        Item,
    )
    is_currently_equipped = models.BooleanField(
        default=False,
    )

    class Meta:
        unique_together = (('item', 'is_currently_equipped'),)

game/apps/match/models.py
from django.db import models
from game.apps.enemies.models import Enemy
from game.apps.characters.models import Character, Type


class Match(models.Model):

    character = models.ForeignKey(
        Character,
        )

    enemy = models.ForeignKey(
        Enemy,
        )

    character_health = models.PositiveIntegerField(
        "Current Character Health",
        max_length=16,
        blank=True,
        )

    enemy_health = models.PositiveIntegerField(
        "Current Enemy Health",
        max_length=16,
        blank=True,
        )

    resource = models.PositiveIntegerField(
        max_length=200,
        default=1,
        )

    finished = models.BooleanField(
        default=False,
        )

    class Meta:
        verbose_name_plural = "Matches"

    def __unicode__(self):
        return self.character.name

    @models.permalink
    def get_absolute_url(self):
            return ("match:detail", (), {
                "pk": self.pk
            })


class Spell(models.Model):

    name = models.CharField(
        max_length=140,
        )
    type = models.ForeignKey(
        Type,
        null=True,
    )
    description = models.TextField(
        null=True,
        )

    damage = models.PositiveIntegerField(
        max_length=15,
        )

    level_required = models.PositiveIntegerField(
        max_length=15,
        null=True,
        )

    turn_cooldown = models.PositiveIntegerField(
        max_length=200,
        )

    def __unicode__(self):
        return self.name


class Attack(models.Model):

    match = models.ForeignKey(
        Match
        )

    spell = models.ForeignKey(
        Spell
        )

    enemy_return_spell = models.ForeignKey(
        Spell,
        null=True,
        related_name='reliation'
        )

    damage_dealt = models.PositiveIntegerField(
        max_length=200,
        null=True,
        )

    damage_taken = models.PositiveIntegerField(
        max_length=200,
        null=True,
        )

    time = models.TimeField(
        null=True,
        )

game/apps/characters/forms.py
from django import forms
from .models import Character
from game.apps.match.models import Match

class CharacterCreate(forms.ModelForm):
    error_css_class = "error"

    class Meta:
        model = Character
        exclude = ['user', 'health', 'xp']


class CreateMatch(forms.ModelForm):

    class Meta:
        model = Match
        exclude = ['character_health', 'enemy_health', 'resource', 'character']

game/apps/characters/views.py
from django.views.generic import DetailView, CreateView, ListView
from .models import Character, Type, Item
from .forms import CharacterCreate, CreateMatch
from game.apps.match.models import Match, Enemy
from django.views.generic.edit import ModelFormMixin
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from game.apps.match.helpers import calculate_player_health, calculate_boss_health


class ShopItems(ListView):
    model = Item

    def get_context_data(self, **kwargs):
        context = super(ShopItems, self).get_context_data(**kwargs)
        # Need to filter by Class(type)
        context['item_list'] = Item.objects.all()
        for item in context['item_list']:
            if  self.request.user >= item.level_required:
                pass
            else:
                context['insufficient'] = "Insufficient Level"

        return context


class CharacterLeaderboard(ListView):
    model = Character

    def get_context_data(self, **kwargs):
        context = super(CharacterLeaderboard, self).get_context_data(**kwargs)
        context['character_list'] = Character.objects.all().order_by('-xp')[:100]
        return context


class CharacterDetail(DetailView):
    model = Character


class CreateMatch(CreateView):
    model = Match
    form_class = CreateMatch

    def get_context_data(self, **kwargs):
        context = super(CreateMatch, self).get_context_data(**kwargs)
        character = get_object_or_404(
            Character,
            pk=self.kwargs.get('pk'),
            user=self.request.user
        )
        context['character'] = character

        context['enemys'] = Enemy.objects.all()
        return context

    def form_valid(self, form):
        Form = form.save(commit=False)
        boss = form.cleaned_data['enemy']
        Form.enemy_health = calculate_boss_health(boss)
        Form.resource = 1
        character = Character.objects.get(pk=self.kwargs['pk'])
        Form.character = character
        Form.character_health = calculate_player_health(character)
        self.object = form.save()
        return super(ModelFormMixin, self).form_valid(form)


class CharacterCreate(CreateView):
    model = Character
    form_class = CharacterCreate

    def form_valid(self, form):
        charactercreate = form.save(commit=False)
        charactercreate.user = self.request.user
        self.object = form.save()
        return super(ModelFormMixin, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CharacterCreate, self).get_context_data(**kwargs)
        context['types'] = Type.objects.all()
        return context

    def get_success_url(self):
        return reverse('character:detail', kwargs={'pk': self.object.pk})


#class DeleteCharacter(UpdateView):
#    model = Character

game/apps/enemies/views.py
from django.shortcuts import render

# Create your views here.

game/apps/match/views.py
from django.views.generic import CreateView, DetailView, ListView
from django.views.generic.edit import ModelFormMixin
from .models import Match, Attack
from game.apps.characters.models import Character
from game.apps.enemies.models import Enemy
from .forms import CreateMatch, AttackForm
from .models import Spell
from django.utils.timezone import now
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse
from .helpers import calculate_player_damage, calculate_boss_damage, calculate_player_health,  calculate_boss_health, calculate_xp


class CreateMatch(CreateView):
    model = Match
    form_class = CreateMatch

    def get_context_data(self, **kwargs):
        context = super(CreateMatch, self).get_context_data(**kwargs)
        context['characters'] = Character.objects.filter(user=self.request.user)
        context['enemys'] = Enemy.objects.all()
        return context

    def form_valid(self, form):
        Form = form.save(commit=False)
        boss = form.cleaned_data['enemy']
        Form.enemy_health = calculate_boss_health(boss)
        Form.resource = 1
        character = form.cleaned_data['character']
        Form.character_health = calculate_player_health(character)
        self.object = form.save()
        return super(ModelFormMixin, self).form_valid(form)


class MatchDetail(DetailView):
    model = Match

    def get_context_data(self, **kwargs):
        context = super(MatchDetail, self).get_context_data(**kwargs)

        context['spells'] = Spell.objects.filter(
            type=self.object.character.type,
            level_required__lte=context['match'].character.level_data()['current_level'],
        )

        match = get_object_or_404(
            Match,
            pk=self.kwargs.get('pk'),
            character__user=self.request.user,
        )

        if self.object.enemy_health == 0:
            context['condition'] = "win"
        else:
            if self.object.character_health == 0:
                context['condition'] = "loose"
            else:
                pass

        context['match'] = match

        cooldown = False

        for spell in context['spells']:
            attack_history_list = Attack.objects.filter(match=122).order_by('-time')[:spell.turn_cooldown]
            print attack_history_list
            for attack_history in attack_history_list:
                if attack_history.spell == attack_history_list:
                    cooldown = True
                    print cooldown
                    print attack_history.spell
                    context['cooldown'] = cooldown
                    break
                else:
                    cooldown = False
                    print cooldown
                    print attack_history.spell
                    context['cooldown'] = cooldown
        return context


class MatchList(ListView):
    model = Match


class AttackForm(CreateView):
    model = Attack
    form_class = AttackForm

    def get_context_data(self, **kwargs):
        context = super(AttackForm, self).get_context_data(**kwargs)
        match = get_object_or_404(
            Match,
            pk=self.kwargs.get('pk'),
            character__user=self.request.user
        )
        context['match'] = match
        return context

    def form_valid(self, form):
        spell = form.cleaned_data['spell']
        attackform = form.save(commit=False)
        match = Match.objects.get(id=self.kwargs['pk'])
        boss_spell = Spell.objects.filter(level_required__lte=match.enemy.level).order_by('?')[0]
        character_level = match.character.level_data()['current_level']
        attackform.enemy_return_spell = boss_spell
        character = match
        attackform.selected_spell = spell
        cooldown = False
        attack_history_list = Attack.objects.filter(match=match).order_by('-time')[:spell.turn_cooldown]

        for attack_history in attack_history_list:
            if attack_history.spell == spell:
                cooldown = True
                break
            else:
                cooldown = False

        if spell.level_required <= character_level and spell.type == match.character.type and cooldown == False:

            if match.finished is False:
                if match.enemy_health <= calculate_player_damage(character, spell):
                    match.enemy_health = 0
                    match.character.xp = match.character.xp + calculate_xp(match)
                    match.finished = True
                else:
                    if match.character_health <= calculate_boss_damage(boss_spell, match):
                        match.character_health = 0
                        match.finished = True
                    else:
                        match.enemy_health = match.enemy_health - calculate_player_damage(character, spell)
                        match.character_health = match.character_health - calculate_boss_damage(boss_spell, match)

            else:
                return super(ModelFormMixin, self).form_valid(form)

            attackform.damage_dealt = calculate_player_damage(match, spell)
            attackform.damage_taken = calculate_boss_damage(boss_spell, match)

            attackform.match = match
            attackform.time = now()
            match.save()
            match.character.save()
            self.object = attackform.save()

            return super(ModelFormMixin, self).form_valid(form)
        else:
            return super(ModelFormMixin, self).form_valid(form)

    def get_success_url(self):
        return reverse('match:detail', kwargs={'pk': self.kwargs['pk']})

game/apps/userprofile/views.py
from django.views.generic import UpdateView
from django.views.generic.edit import ModelFormMixin
from .forms import UserProfileForm
from .models import UserProfile


class UserProfilePage(UpdateView):
    model = UserProfile
    success_url = '/settings/'
    form_class = UserProfileForm

    def form_valid(self, form):
        self.object = form.save()
        return super(ModelFormMixin, self).form_valid(form)

game/views.py
from django.views.generic import ListView
from game.apps.characters.models import Character

class Homepage(ListView):
    model = Character
    template_name = 'site/homepage.html'

    def get_context_data(self, **kwargs):
        context = super(Homepage, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated():
            context['characters'] = Character.objects.filter(user=self.request.user)
        else:
            pass
        return context

game/templates/characters/character_detail.html
{% extends "base.html" %}
{% block content %}
{% with level_data=character.level_data %}
<div class="xp-bar" data-width="{{ level_data.xp_percentage }}"></div>
<div class="row">
<div class="large-4 columns">
        <div class="panel">
            <h3>Match History</h3>
            <hr>
            <ul class="history-listing">
            {% for match in character.match_set.all  %}

                <li>{{ match.character }} vs {{ match.enemy }}</li>

            {% endfor %}
            <!-- <li>{{ level_data.xp_percentage}}% Until Next Level</li> -->
            </ul>
        </div>
    </div>

    <div class="large-8 columns">
        <h1>{{ character.name }} <small>{{ character.type }}</small>

            <small><a href="/" class="right switch-char">Switch Character</a></small>
        </h1>
        <small class="level">Level {{ level_data.current_level }}</small>
        <hr>
    </div>
    <div class="large-8 columns">
        <div class="panel clearfix">

                <img src="/static/assets/character.png" class="left">

            <h3 class="left inventory">Inventory</h3>

            <ul class="left inv-item">
                {% for bag in character.characteritem_set.all  %}
                <li><img src="/media/{{ bag.item.image }}"></li>
                {% endfor %}
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
            </ul>
        </div>
        <a href="/character/{{ character.id }}/create" class="button small">Start Match</a>
        <a href="/character/{{ character.id }}/shop/" class="button small">View Shop</a>
        <a href="/character/{{ character.id }}/spells/" class="button small">See Available Spells</a>
</div>

    <script src="/static/js/countdown.min.js"></script>
{% endwith %}
{% endblock %}

{% block js %}
<script>
$(function() {
    $('.xp-bar').width($('.xp-bar').data('width') + '%');
});ws
</script>
{% endblock %}
{% block url %}
    {{ character.get_absolute_url }}
{% endblock %}

game/templates/characters/character_form.html
{% extends "base.html" %}
{% block content %}
<style type="text/css">
input.classes {
display: none;
}

input.classes[type="radio"]:checked+label{
    background: #222;

}
input.classes[type="radio"]+label {
    margin: 0;
}
.classlabel {
background: #333;
height: 247px;
padding-top: 92px;
font-size: 26pt;
text-align: center;
transition: background .25s ease-in-out;
-moz-transition: background .25s ease-in-out;
-webkit-transition: background .25s ease-in-out;
color: #ccc;
width:33%;
margin-bottom: 4px !important;
}
.classlabel label:hover, label:active, input:hover+label, input:active+label {
    background: #222;
}
</style>
    <div class="row">
        <div class="large-12 columns">
            <h1>Create a character</h1>
            <hr>
        </div>
        <div class="large-12 columns left">
            <form action="" method="post">
                {% csrf_token %}
                <div class="large-4 columns">
                                    <h3>Characters name: {% if form.name.errors %}<small class="error">Character with this name already exists</small>{% endif %}</h3>
                </div>
                <div class="large-8 columns">{{ form.name }}</div>
                <hr>
                <h3>Choose your class:</h3><hr>
                {% for type in types %}
                <input type="radio" name="type" class="classes" value="{{ type.id }}" id="{{ type.name }}">
                <label for="{{ type.name }}" class="classlabel">{{ type.name }}</label>
                {% endfor %}

                <hr>

                <input type="submit" value="Create Character" class="button large">
            </form>
        </div>
    </div>



{% endblock %}

game/templates/characters/character_list.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        <div class="large-12 columns">
            <h1>Leaderboard</h1>
            <hr>
            <p>Here are the top 100 characters!</p>
            <ol>
                {% for character in character_list %}
                    <li><a href="/character/{{ character.id }}">{{ character.name }}</a></li>
                {% endfor %}
            </ol>
        </div>
    </dov>
{% endblock content %}

game/templates/characters/item_list.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="large-3 columns">
        <form action="">
        <input type="text" name="q" placeholder="Search for a item...">
        </form>
        <ul class="shop-classes">
            <li><a href="/">Example Class</a></li>
        </ul>
    </div>
    <div class="large-9 columns" data-equalizer>
        <h1>Shop </h1>
        <hr>


        <div id="effect-1" class="effects clearfix">
        {% for item in item_list %}
        <div class="large-4 columns left" data-equalizer-watch>
            <div class="img">
                <small class="price">Price: ${{ item.worth }}</small>
                <img src="http://piq.codeus.net/static/media/userpics/piq_47498_400x400.png" alt="">
                <hr>
                <h3>{{ item.name }}</h3>
                <div class="overlay">
                <a href="#" class="expand">+</a>

                <a class="close-overlay hidden">x</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}
{% block js %}
<script type="text/javascript">
$(document).ready(function(){
    if (Modernizr.touch) {
        // show the close overlay button
        $(".close-overlay").removeClass("hidden");
        // handle the adding of hover class when clicked
        $(".img").click(function(e){
            if (!$(this).hasClass("hover")) {
                $(this).addClass("hover");
            }
        });
        // handle the closing of the overlay
        $(".close-overlay").click(function(e){
            e.preventDefault();
            e.stopPropagation();
            if ($(this).closest(".img").hasClass("hover")) {
                $(this).closest(".img").removeClass("hover");
            }
        });
    } else {
        // handle the mouseenter functionality
        $(".img").mouseenter(function(){
            $(this).addClass("hover");
        })
        // handle the mouseleave functionality
        .mouseleave(function(){
            $(this).removeClass("hover");
        });
    }
});
</script>
{% endblock js %}